# -*- coding: utf-8 -*-
"""Compilation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYrAlU7_r8S_e2pABQh-yeAXxZ4qWqmx
"""

high_income = input('Is your income high? (True/False): ').strip().lower()
good_score = input('Is your credit score good? (True/False): ').strip().lower()

message = ''

if high_income == 'true':
  message += "You have a good chance of buying a car\n"
elif high_income == 'false':
  message += 'You have a low chance of buying a car\n'
else:
  print('Invalid input: enter true or false')

if good_score == 'true':
    message += 'You have a good credit score. \n'
elif good_score == 'false':
    message += 'You have a low credit score. \n'
else:
    print('Invalid input for credit score: Enter true or false.')

if 'Invalid input' not in message:
  print(message)

number = input('Enter a number: ')

number = int(number)

if number % 2 == 0:
  print('The number is even')
else:
  print('The number is odd')

# a list of departments in an IT company

departments = ["Software Development", "Data Science", "Cybersecurity", "IT Support", "Cloud Computing"]

depart = input("Enter another department into departments: ")

departments.append(depart)

print(departments)

departments.insert(0, "Network Engineering")

print(departments)

departments.remove("Cybersecurity")

print(departments)

departments.pop(1)

print(departments)

departments.sort()

print(departments)

departments.sort(reverse=True)

print(departments)

departments.extend(["Software Development", "Data Science", "Cybersecurity", "IT Support", "Cloud Computing"])

print(departments)

departments.reverse()

print(departments)

departments.clear()

print(departments)

# create a list of positions in an AI department and another list in an IT support department

ai_positions = ["AI Engineer", "Machine Learning Specialist", "Data Scientist", "AI Researcher"]
it_support_positions = ["Help Desk Technician", "Network Administrator", "System Administrator", "IT Support Specialist"]

ai_positions.extend(it_support_positions)

print(ai_positions)

it_support_positions.pop(0)

print(it_support_positions)

ai_positions.sort()

print(ai_positions)

it_support_positions.sort()

print(it_support_positions)

# prompt: practice working with dictionaries

# Create a dictionary
student = {
    "name": "Alice",
    "age": 20,
    "major": "Computer Science",
    "grades": [85, 90, 92]
}

# Accessing values
print(student["name"])  # Output: Alice
print(student["age"])   # Output: 20

# Modifying values
student["age"] = 21
print(student["age"])  # Output: 21

# Adding new key-value pairs
student["city"] = "New York"
print(student)

# Removing key-value pairs
del student["city"]
print(student)

# Checking if a key exists
if "major" in student:
  print("Major key exists")

# Iterating through the dictionary
for key, value in student.items():
  print(key, value)

# Getting all keys
keys = student.keys()
print(keys)

# Getting all values
values = student.values()
print(values)

employee = {"Name": "Dakalo",
            "Surname": "Nemutaduni",
            "Age": 25,
            "Position": "General worker",
            }

print(employee)

print(employee["Name"])

print(employee["Surname"])

print(employee["Age"])

print(employee["Position"])

employee["Position"] = "Data Scientist"

print(employee)

employee["Salary"] = 50000

print(employee)

salary = employee.get("Salary")

if salary in employee:
  print("Salary does exist in employee dictionary")
else:
  print("Salary does not exist in employee dictionary")

for key, value in employee.items():
  print(key, value)

keys = employee.keys()
print(keys)

values = employee.values()
print(values)

# prompt: practice for loops

# Loop through a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
  print(fruit)

# Loop through a string
for letter in "banana":
  print(letter)

# Loop through a range of numbers
for i in range(6):
  print(i)

# Loop through a range with a start and end value
for i in range(2, 6):
  print(i)

# Loop through a range with a start, end and step value
for i in range(2, 30, 3):
  print(i)

employees = ["Dakalo", "Tom", "Brandon"]

for  employee in employees:
  print(employee)

for i in range(len(employees)):
  print(employees[i])

for letter in "Dakalo":
  print(letter)

for i in range (10):
  print(i)

for i in range(2, 6):
  print(i)

for i in range(2, 12, 2):
  print(i)

# prompt: practice while loops

# Initialize a counter
count = 0

# While loop that continues as long as count is less than 5
while count < 5:
  print("Count:", count)
  count += 1  # Increment the counter

# Example with user input
number = int(input("Enter a number: "))
while number < 10:
  print("The number is less than 10. Please enter a larger number.")
  number = int(input("Enter a number: "))
print("The number is greater than or equal to 10.")

count = 0

while count < 10:
  print("Count: ", count)
  count += 1

number = int(input("Enter a number: "))

while number < 5:
  print("Enter a larger number than 5")
  number = int(input("Enter a number: "))

print("The number is greater than or equal to 5")

